# ??????????????????????????????????????????????????????????????????????????????
# Environment: DEV
# Activate with: mvn test -Denv=dev
# ??????????????????????????????????????????????????????????????????????????????

base.url       = https://jsonplaceholder.typicode.com
auth.token     = ${DEV_AUTH_TOKEN}
max.retries    = 3
retry.delay.ms = 500