# ??????????????????????????????????????????????????????????????????????????????
# Environment: QA  (default)
# Activate with: mvn test -Denv=qa
# ??????????????????????????????????????????????????????????????????????????????

base.url        = https://jsonplaceholder.typicode.com
api.timeout.ms  = 15000
retry.count     = 1
auth.token      = no-auth-required
log.level       = INFO
parallel.threads = 5