name: API Automation Tests
run-name: "🚀 API Automation Tests — ${{ github.ref_name }} branch"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create config.properties
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/config.properties << EOF
          base.url=https://jsonplaceholder.typicode.com
          base.path=
          api.key=none
          default.user.id=2
          default.timeout=10000
          EOF

      - name: Run API Tests
        run: mvn clean test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 30

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 30